server:
  port: 8084

spring:
  application:
    name: servicio-notificaciones
  config:
    import: optional:configserver:${CONFIG_URL:http://localhost:8888}
  cloud:
    config:
      fail-fast: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
