server:
  port: ${PORT:8087}

spring:
  application:
    name: servicio-pagos
  config:
    import: optional:configserver:${CONFIG_URL:http://localhost:8888}
  cloud:
    config:
      fail-fast: false
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

springdoc:
  swagger-ui:
    path: /swagger-ui.html
