# ============================================================
#  BFF WEB - backend dedicado al portal de navegador
# ============================================================
spring.application.name=bff-web
server.port=8081

banco.core-api.url=${CORE_API_URL:http://localhost:8080}
banco.core-api.timeout-conexion-ms=2000
banco.core-api.timeout-lectura-ms=5000

# Compresion: las respuestas de este BFF son grandes a proposito.
server.compression.enabled=true
server.compression.mime-types=application/json
server.compression.min-response-size=2048

springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.bank.xyz.bff=INFO
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %-28.28logger{0} : %msg%n
