banco:
  eventos:
    destino: banco.eventos.transaccion
    alertas: banco.eventos.alertas

spring:
  artemis:
    mode: ${ARTEMIS_MODE:native}
    broker-url: ${ARTEMIS_URL:tcp://localhost:61616}
  jms:
    pub-sub-domain: true
